name: Rust CI/CD

on:
  push:
    branches: [ "main", "dev", "dev-*", "play", "play-*" ]  # 推送到分支时触发
    tags: [ "*" ]         # 推送 Tag 时触发
  pull_request:
    branches: [ "main" ]  # 创建 PR 时触发

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release:
    if: startsWith(github.ref, 'refs/tags/')  # 仅在 Tag 推送时运行
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build release binary
      run: cargo build --release

    - name: Extract package name from Cargo.toml
      id: extract_name
      run: |
        PACKAGE_NAME=$(grep -m 1 '^name = ' Cargo.toml | sed -E 's/name = "(.*)"/\1/')
        echo "package_name=$PACKAGE_NAME" >> $GITHUB_ENV

    - name: Archive binary
      run: |
        mkdir -p artifacts
        cp target/release/${{ env.package_name }} artifacts/
        tar -czf artifacts/${{ env.package_name }}.tar.gz -C artifacts ${{ env.package_name }}

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/${{ env.package_name }}.tar.gz  # 指定要上传的文件路径
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
